### Библиотеки
- Библиотеки для обработки данных: [NumPy](https://numpy.org) и [Pandas](https://pandas.pydata.org).
- Библиотеки для визуализации данных: [Matplotlib](https://matplotlib.org)  и [Seaborn](https://seaborn.pydata.org/#).

### NumPy

**NumPy** — библиотека языка Python, позволяющая удобно работать с многомерными массивами и матрицами, содержащая математические функции. Кроме того, NumPy позволяет векторизовать многие вычисления, имеющие место в машинном обучении. 

 - [numpy](http://www.numpy.org)
 - [numpy tutorial](http://cs231n.github.io/python-numpy-tutorial/)
 - [100 numpy exercises](http://www.labri.fr/perso/nrougier/teaching/numpy.100/)

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 4, 5])

In [3]:
matrix = np.array([[1, 2], [2, 3], [3, 4]])

In [6]:
matrix_3d = np.array([matrix, 2 * matrix + 5])

In [7]:
arr.ndim, matrix.ndim, matrix_3d.ndim

(1, 2, 3)

In [9]:
print(arr.shape, matrix.shape, matrix_3d.shape)

(4,) (3, 2) (2, 3, 2)


In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2, 3, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [12]:
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
# единичная матрица
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [16]:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.linspace(3, 14, 18)

array([ 3.        ,  3.64705882,  4.29411765,  4.94117647,  5.58823529,
        6.23529412,  6.88235294,  7.52941176,  8.17647059,  8.82352941,
        9.47058824, 10.11764706, 10.76470588, 11.41176471, 12.05882353,
       12.70588235, 13.35294118, 14.        ])

In [18]:
np.linspace(3.5, 14.5, 100)

array([ 3.5       ,  3.61111111,  3.72222222,  3.83333333,  3.94444444,
        4.05555556,  4.16666667,  4.27777778,  4.38888889,  4.5       ,
        4.61111111,  4.72222222,  4.83333333,  4.94444444,  5.05555556,
        5.16666667,  5.27777778,  5.38888889,  5.5       ,  5.61111111,
        5.72222222,  5.83333333,  5.94444444,  6.05555556,  6.16666667,
        6.27777778,  6.38888889,  6.5       ,  6.61111111,  6.72222222,
        6.83333333,  6.94444444,  7.05555556,  7.16666667,  7.27777778,
        7.38888889,  7.5       ,  7.61111111,  7.72222222,  7.83333333,
        7.94444444,  8.05555556,  8.16666667,  8.27777778,  8.38888889,
        8.5       ,  8.61111111,  8.72222222,  8.83333333,  8.94444444,
        9.05555556,  9.16666667,  9.27777778,  9.38888889,  9.5       ,
        9.61111111,  9.72222222,  9.83333333,  9.94444444, 10.05555556,
       10.16666667, 10.27777778, 10.38888889, 10.5       , 10.61111111,
       10.72222222, 10.83333333, 10.94444444, 11.05555556, 11.16

In [19]:
np.array([1, 2, 3, 4, 5], dtype=float)

array([1., 2., 3., 4., 5.])

In [22]:
np.arange(10).reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
A = np.arange(10).reshape((2, 5))
A.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [23]:
np.transpose(A)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [24]:
B = np.arange(8).reshape((2, 4))

In [25]:
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [26]:
B = np.arange(8).reshape((2, 4))

# A * B
print(A.T.dot(B))
print(np.dot(A.T, B))

[[20 25 30 35]
 [24 31 38 45]
 [28 37 46 55]
 [32 43 54 65]
 [36 49 62 75]]
[[20 25 30 35]
 [24 31 38 45]
 [28 37 46 55]
 [32 43 54 65]
 [36 49 62 75]]


In [27]:
A.dot(B)

ValueError: shapes (2,5) and (2,4) not aligned: 5 (dim 1) != 2 (dim 0)

In [28]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [29]:
np.sin(A)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [32]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
np.max(A), np.min(A)

(9, 0)

In [31]:
np.max(A, axis=0)

array([5, 6, 7, 8, 9])

In [33]:
np.max(A, axis=1)

array([4, 9])

In [34]:
A[:, 2:4]

array([[2, 3],
       [7, 8]])

In [36]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
A % 3 == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [37]:
A[A % 3 == 0]

array([0, 3, 6, 9])

In [40]:
A = np.random.randint(0, 100, (4, 5))
A

array([[84, 71, 40, 74, 62],
       [27, 17, 30, 88, 11],
       [11, 94, 91,  0, 35],
       [91, 58, 16, 94, 43]])

In [41]:
A[(A % 3 == 0) | (A % 7 == 0)]

array([84, 27, 30, 91,  0, 35, 91])

In [42]:
A[(A % 3 == 0) & (A % 7 == 0)]

array([84,  0])

In [43]:
A = np.arange(9).reshape((3, 3))
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
A ** 3

array([[  0,   1,   8],
       [ 27,  64, 125],
       [216, 343, 512]])

In [46]:
A.sum(axis=1)

array([ 3, 12, 21])

#### Зачем?

Зачем необходимо использовать NumPy, если существуют стандартные списки/кортежи и циклы?

Основаная причина заключается в скорости работы. Попробуем посчитать сумму поэлементых произведений 2 больших векторов:

In [47]:
A_quick_arr = np.random.normal(size = (1000000,))
B_quick_arr = np.random.normal(size = (1000000,))

In [48]:
A_quick_arr[:5]

array([ 0.56470364,  2.00378689,  1.74635017,  1.2320923 , -1.03369476])

In [49]:
A_slow_list = list(A_quick_arr)
B_slow_list = list(B_quick_arr)

In [54]:
%%timeit -n 10

ans = 0
n = len(A_slow_list)

for i in range(n):
    ans += A_slow_list[i] * B_slow_list[i]
ans

219 ms ± 9.93 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [56]:
%%timeit -n 50

A_quick_arr.dot(B_quick_arr.T)

525 µs ± 76.3 µs per loop (mean ± std. dev. of 7 runs, 50 loops each)


**Задание 1.** По заданному одномерному numpy-массиву найдите все элементы в нем, которые удовлетворяют двум условиям:
* остаток при делении на 7 больше, чем 3
* остаток при делении на 11 меньше 4

**Задание 2.** По заданному двумерному numpy-массиву $A$ найдите сумму квадратов всех его элементов и поделите на количество элементов в матрице. К полученному результату прибавьте минимум заданной матрицы на втором столбце и максимум на предпоследнем столбце (гарантируется, что в матрице не менее двух столбцов).

**Задание 3.** Напишите функцию, которая по заданному одномерному numpy-массиву $A$ и числу $x$ возвращает позицию наиближайшего к $x$ элемента в матрице $A$. Попробуйте придумать наиболее эффективную реализацию. Замерьте время выполнения вашего решения.

In [57]:
arr = np.random.randint(0, 10000, 300)

In [59]:
arr

array([ 528, 8350, 1251, 1200, 8933, 6448, 2145, 5125, 6105, 2207, 7083,
       2711, 6382, 5218, 2607, 5392,  870, 9774, 7249, 1606, 1739, 8444,
       8350, 7679, 4492, 4518, 4126, 4865, 5502, 4660, 4671, 4883, 9097,
       6332, 8806, 3019,  839, 6130, 6789, 4423, 8074, 2186, 3362, 6232,
        982, 7797, 1448, 9660, 9221, 2023, 6382, 4810, 2181, 3681, 2379,
       7643, 6902, 3988, 2816, 6063, 7681,  107, 7067, 8090, 4745, 9258,
       8026, 3828, 8468, 7475, 7691, 9636, 7088,  901, 2784, 3252,  207,
        576, 8683, 7281, 4374, 2029, 3787, 5238, 5790, 6290, 7857, 7555,
       1531, 6152, 1993, 9935, 7901, 5090, 9113, 3696, 5752, 3244, 1648,
       7261, 5793, 3696, 6291, 9765,  281, 8530, 8270,  104, 6912, 1319,
       5237, 6908, 6547, 5603,  474, 5830, 6766, 2580, 1868,  828, 5921,
       6896, 7548, 1075, 3065,  219, 1745, 8088, 8340,  115, 3054, 7887,
        378, 1566, 9806, 5674, 4272, 2849, 6777,  683, 5926,  674, 3805,
       3596, 4076,  829, 6810,  551, 3471, 1093, 55

In [58]:
arr[(arr % 7 > 3) & (arr % 11 < 4)]

array([8350, 6382, 7249, 8350, 9097,  839, 6130, 6789, 4423, 6382, 2181,
       2379, 3828, 7691, 9636, 2784, 1531, 6152, 1993, 7901, 6908,  474,
       5830, 6766, 5921, 7887,  683, 6810,  551, 8230, 6151,  454, 9482,
       8636, 9769, 7285, 1070, 8110, 6634, 6822, 9251, 8077, 2477, 5765,
       5723, 2533, 4323,  298])

In [60]:
A = np.array(
    [
        [2, 4, 7, 1],
        [7, 8, 5, 10],
        [6, 3, 6, 4],
        [20, 3, 1, 2],
        [2, 8, 5, 11],
    ]
)

In [63]:
A.size

20

In [64]:
np.sum(A ** 2) / A.size + A[:, 1].min() + A[:, -2].max()

61.65

In [69]:
%%time

A = np.arange(10.1, 504.2, 3.3)
x = 103

index = np.abs(A - x).argmin()
print(index)
print(A[index])

28
102.49999999999997
CPU times: user 354 µs, sys: 188 µs, total: 542 µs
Wall time: 386 µs
